spring.jpa.open-in-view=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATSOURCE_URL}
spring.datasource.username=${SPRING_DATSOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
aws.eventBridge.bus=
aws.s3.bucket=
aws.s3.region=