spring.jpa.open-in-view=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATSOURCE_URL:jdbc:postgresql://localhost:5432/async_mailing_db}
spring.datasource.username=${SPRING_DATSOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Pa$$Na$$aIW0rd}
aws.eventBridge.bus=
aws.s3.bucket=